/**
 * ADZEN is a popular advertising firm in your city that owns all n billboard locations on Main street.
 * The city council passed a new zoning ordinance mandating that no more than k consecutive billboards
 * may be up at any given time. For example, if there are n = 3 billboards on Main street and k = 1,
 * ADZEN must remove either the middle billboard, the first two billboards, the last two billboards or
 * the first and last billboard.
 * Being a for-profit company, ADZEN wants to lose as little advertising revenue as possible when removing
 * the billboards. They want to comply with the new ordinance in such a way that the remaining billboards
 * maximize their total revenues (i.e., the sum of revenues generated by the billboards left standing on
 * Main street).
 * Given n. k, and the revenue of each of the n billboards, find and print the maximum profit that ADZEN
 * can earn while complying with the zoning ordinance. Assume that Main street is a straight, contiguous
 * block of n billboards that can be removed but cannot be reordered in any way.
 * For example, if there are n = 7 billboards, and k = 3 is the maximum number of consecutive billboards
 * that can be active, with revenues = [5, 6, 4, 2, 10, 8, 4], then the maximum revenue that can be
 * generated is 37:5+6+4+10+8+4=37.
 *
 * Function Description
 * Complete the billboards function in the editor below. It should return an integer that represents the maximum
 * revenue that can be generated under the rules.
 *
 * billboards has the following parameter(s):
 * k: an integer that represents the longest contiguous group of billboards allowed
 * revenue: an integer array where each element represents the revenue potential for a billboard at that index
 * Input Format
 * The first line contains two space-separated integers, n (the number of billboards) and k (the maximum number
 * of billboards that can stand together on any part of the road). Each line of the n subsequent lines contains
 * an integer denoting the revenue value of billboard & (where 0 < i < n).
 *
 * Output Format
 * Print a single integer denoting the maximum profit ADZEN can earn from Main street after complying with the
 * city’s ordinance.
 *
 */

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Billboards {

    public static void main(String[] args) {
        Integer[] revenues = {5, 6, 4, 0, 1, 0, 5};
        System.out.println(billboards(5, Arrays.asList(revenues)));
    }

    //Implement this method
    static int billboards(int k, List<Integer> revenue) {

        //Create a list that supports removal
        revenue = new ArrayList<>(revenue);

        //Remove the lowest elements required for evenly dividing by k, keeping the order
        if (revenue.size() % k != 0) {
            int toRemove = 1;
            while ((revenue.size() - toRemove) % k != 0) {
                toRemove++;
            }
            //Remove the smallest 'toRemove' items
            for (; toRemove > 0; toRemove--) {
                revenue.remove(Collections.min(revenue));
            }
        }
        //Perform the calculation
        int subCount = 0, subtotal = 0, maxProfit = 0;
        for (int i = 0; i < revenue.size(); i++) {
            subtotal += revenue.get(i);
            subCount++;
            if (subCount == k) {
                maxProfit += subtotal;
                subCount = 0;
                subtotal = 0;
            }
        }
        return maxProfit;
    }

}
